version: "3.8"

services:
  tgi_service:
    image: ghcr.io/huggingface/text-generation-inference:2.1.0
    container_name: tgi-service
    ports:
      - "8085:80"
    volumes:
      - ${HF_CACHE_DIR}:/data
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
    command: --model-id ${LLM_MODEL_ID}